# Generated by Django 3.0.5 on 2020-04-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stanford_theater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
