# Generated by Django 3.0.5 on 2020-04-25 02:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stanford_theater', '0004_movie_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
