# Generated by Django 3.0.5 on 2020-04-25 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stanford_theater', '0006_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stanford_theater.Movie'),
        ),
    ]
