# Generated by Django 3.0.5 on 2020-04-25 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stanford_theater', '0007_schedule_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='time',
        ),
    ]
